### ISSUE TITLE
Describe what GSequencer does

### ISSUE THREAD

**Issue by probonopd** [gsequencer/gsequencer#40]
The first(!) sentences in the READE should describe what this software does (before talking about licensing), in order to make it easier for newcomers to find out what this application is all about.

Something like:

> GSequencer is an application that allows you to create, record and play back notation (music). There are two different modes for creating notes, one with fixed length, the other with varying length. Note recording is possible via MIDI (Musical Instrument Digital Interface). For playback, it uses a tree structure to process the various modules.

**Comment by joelkraehemann** [comment]
Yeah, I am not happy with the README, neither.

**Comment by joelkraehemann** [comment]
Just applied the changes:

https://github.com/gsequencer/gsequencer/blob/2.1.x/README

**Comment by joelkraehemann** [comment]
thank you for your feedback.
