### ISSUE TITLE
glib

### ISSUE THREAD

**Issue by geekositalia** [gsequencer/gsequencer#44]
Hi, im a geekosdaw project admin, for opensuse on obs.

It's not really issue but. glib versione supporto its to high for leap (we distribute official support only for current stable leap).

Requested 'glib-2.0 >= 2.56.0' but version of GLib is 2.54.3

we would be happy if there was a patch for this

**Comment by geekositalia** [comment]
This is a project page http://geekosdaw.tuxfamily.org/

**Comment by joelkraehemann** [comment]
Hi geekositalia,

Nice to know someone cares, I provide a patch. Since, I compile it on LFS
7.9 with some modifications:

http://git.savannah.nongnu.org/cgit/gsequencer.git/tree/configure.ac?h=3.3.x#n353

... might be AgsServer does some problems.

Thank you!

regards,
Joël


Am Do., 4. Juni 2020 um 17:16 Uhr schrieb geekositalia <
notifications@github.com>:

**Comment by joelkraehemann** [comment]
I am just downloading:

https://download.opensuse.org/distribution/leap/15.1/iso/openSUSE-Leap-15.1-DVD-x86_64.iso

**Comment by joelkraehemann** [comment]
Just install a VM ...

![Screenshot_opensuse15 1_2020-06-04_19:15:29](https://user-images.githubusercontent.com/12599056/83790086-f0e47d00-a697-11ea-9733-7a0ba2371bbe.png)

Please have a little patience.

**Comment by joelkraehemann** [comment]
![Screenshot_opensuse15 1_2020-06-04_19:32:31](https://user-images.githubusercontent.com/12599056/83791528-35711800-a69a-11ea-99e9-0aaaeb1be515.png)

approximation 1 - 2 hours in a optimistic way

**Comment by joelkraehemann** [comment]
Is gsequencer-3.3.10.tar.gz the correct version?

![Screenshot_opensuse15 1_2020-06-04_20:01:43](https://user-images.githubusercontent.com/12599056/83794459-53407c00-a69e-11ea-98e8-8644350bc70e.png)

**Comment by joelkraehemann** [comment]
May be something went wrong ...

![Screenshot_opensuse15 1_2020-06-04_20:06:44](https://user-images.githubusercontent.com/12599056/83794904-f7c2be00-a69e-11ea-9320-ed1cc23dea43.png)

Update just specified wrong package name: gtk3-devel is correct

**Comment by joelkraehemann** [comment]
Here we go:

![Screenshot_opensuse15 1_2020-06-04_20:23:23](https://user-images.githubusercontent.com/12599056/83796430-4f622900-a6a1-11ea-8d42-be170b1e12ac.png)

I just added more conditional builds in configure.ac

**Comment by joelkraehemann** [comment]
The fix as screenshot :-)

![Screenshot_opensuse15 1_2020-06-04_20:35:43](https://user-images.githubusercontent.com/12599056/83797479-01e6bb80-a6a3-11ea-97c3-feb1759280cd.png)

... I just provide you a patch and gsequencer-v3.3.11.tar.gz containing the changes.

**Comment by joelkraehemann** [comment]
Here you are:

http://git.savannah.nongnu.org/cgit/gsequencer.git/commit/?h=3.3.x&id=a5b350c359a65c40c09d10883c0343d21e8bf3cd

This is the actual fix.

**Comment by joelkraehemann** [comment]
Just running `make distcheck`.

**Comment by joelkraehemann** [comment]
approximation 1 - 2 hours until provided in openSUSE build service.

**Comment by joelkraehemann** [comment]
FYI, @geekositalia I won't provide a configure script that detects glib-2.0 version, because I don't know how to make it portable ... Especially for Mac OS X and Windows 10.

What do you think about patching configure.ac?

Might be I just have to provide some environment variables not figured out, yet.

**Comment by joelkraehemann** [comment]
Let's see if it builds:
https://build.opensuse.org/package/show/home:jkraehemann/gsequencer

**Comment by joelkraehemann** [comment]
The request has been submitted on factory:

https://build.opensuse.org/request/show/811616

for me it is done.
