### ISSUE TITLE
Directly using g_strdup() to copy the return value of snd_device_name_get_hint() can cause a memory leak

### ISSUE THREAD

**Issue by Zero0one1** [gsequencer/gsequencer#53]
According to the [ALSA library document](https://www.alsa-project.org/alsa-doc/alsa-lib/group___control.html#ga8546500ca828392f03f5bba2e7813874), we should free the return value of `snd_device_name_get_hint()` after use. Otherwise, it will cause a memory leak. These 3 cases below directly copy the return value using `g_strdup()` without freeing it. We should reorganize the code and free the return value using `free()`.
https://github.com/gsequencer/gsequencer/blob/a0b72b776687e6e5c5ce4e1b44962c29877d806d/ags/audio/ags_devin.c#L1558-L1559
https://github.com/gsequencer/gsequencer/blob/a0b72b776687e6e5c5ce4e1b44962c29877d806d/ags/audio/ags_devout.c#L1648-L1649
https://github.com/gsequencer/gsequencer/blob/a0b72b776687e6e5c5ce4e1b44962c29877d806d/ags/audio/ags_midiin.c#L1095-L1096

**Comment by joelkraehemann** [comment]
thank you for reporting the bug.

**Comment by joelkraehemann** [comment]
https://github.com/gsequencer/gsequencer/releases/tag/3.8.7
