### ISSUE TITLE
Release process?

### ISSUE THREAD

**Issue by mxmilkiib** [gsequencer/gsequencer#54]
Hello! https://libreav.org/updates / https://libreav.org/river is properly on the go now, though I was wondering if I could make a proposal as it is often rather crowded with AGS releases;

I see you're adding description annotations every several releases (3.8.3, 3.7.48, 3.7.44, 3.7.35, 3.7.33) rather than on all of them. While I do appreciate the aphorism of "release early, release often", might it be possible to have a more prominent major and minor release system, reflected in the version string, so that the minor releases could be filtered from libreav, just to balance things out there slightly, with the major release (idk, maybe every x.x.0?) descriptions being an aggregate enumeration of the changes/fixes since the last major release?

(I also think collating the changes like that will give folk more insight into and reason to investigate AGS.)

**Comment by joelkraehemann** [comment]
Hi,

I am able to work full-time on GSequencer. If you check latest minor release it took 3-4 months to develop. When I find an annoying bug if its newly introduced or old I usually do a micro release.

In view of the next debian stable version I worked parallel on 3.7.x and 3.8.x. This usually doesn't happen.

Major releases are time to break ABI, its about get rid of old code which was replaced by newer one e.g. ags-fx effect processing engine.

If you need more information on what is going on, please check news on savannah:

http://savannah.nongnu.org/news/?group=gsequencer

The NEWS file in the source tree provides additional information, so does the ChangeLog file.

From my twitter account:

> gsequencer-news: for the initial release of 3.8.x branch following changes were done:
> 
> 341 files changed, 24162 insertions(+), 10181 deletions(-)

**Comment by mxmilkiib** [comment]
Cool, I'll just filter all non x.x.0 releases then

**Comment by mxmilkiib** [comment]
Ah, sadly I cannot filter for that; given a limitation of the Drupal Feeds system and the format of the AGS GH /releases.atom, I cannot filter for non-microreleases. I'll remove the AGS feed aggregation for now (as I'm looking for RSS/Atom feeds for just major and minor releases). AGS will remain in the libreav software DB though.

**Comment by joelkraehemann** [comment]
You could check AppImage it is lower frequented.

**Comment by joelkraehemann** [comment]
I provide the AppImage by releases:

https://github.com/gsequencer/gsequencer/releases
