### ISSUE TITLE
How much C++ is there in this project? Or is this possibly C-only?

### ISSUE THREAD

**Issue by mavavilj** [gsequencer/gsequencer#57]
How much C++ is there in this project (yes I can see 1.2%, but where is it)? Or is this possibly C-only?

https://github.com/gsequencer/gsequencer/search?l=c%2B%2B&p=1

makes it seem like it's only in VST3 and some "ags". Does this imply that the program itself is in C, but C++ is in "some external libs"?

**Comment by joelkraehemann** [comment]
Hi,

It depends. Actually it is C only except libags_vst.so is a C++ wrapper. On macos we use objective c compiler.

regards,
Joël

**Comment by mavavilj** [comment]
What about the license? Is it strictly GPL, since I'd ideally like BSD or MIT.

**Comment by luzpaz** [comment]
This ticket is probably resolved.
