### ISSUE TITLE
segfault when running from gnome shell

### ISSUE THREAD

**Issue by 2-www** [gsequencer/gsequencer#63]
i have gsequencer installed from flathub on debian, when i try to start it from gnome's search, it segfaults: `kernel: gsequencer[116204]: segfault at 0 ip 00007fa5d5cd155d sp 00007ffdbd2e8528 error 4 in libc.so.6[7fa5d5b90000+166000] likely on CPU 1 (core 1, socket 0)`
i tried to debug it with gdb, and it started normally
it always segfaults when i start it from gnome but works if i do `flatpak run org.nongnu.gsequencer.gsequencer` in a terminal

**Comment by 2-www** [comment]
(i have cleared data yes)

**Comment by joelkraehemann** [comment]
Hi,

Thank you for reporting the problem. Do you have systemd-coredump installed? Might be you are able to share a stack-trace?

Further, have you installed pipewire-pulse?

What debian version are you running?

**Comment by joelkraehemann** [comment]
can confirm the crash. gsequencer_main.c doesn't check boundaries of argc in main if filename is ommited.

**Comment by joelkraehemann** [comment]
should be fixed by this commit.

https://github.com/gsequencer/gsequencer/commit/48c28cdca1aaf612ed1dc59c8952f8fe695b5be8
