### ISSUE TITLE
can't export sound

### ISSUE THREAD

**Issue by 2-www** [gsequencer/gsequencer#67]
clicking "export" in "export to audio data" dialog just starts playing the audio as if you pressed the play button, and doesn't export into the selected destination file

**Comment by joelkraehemann** [comment]
What suffix are you using?

**Comment by 2-www** [comment]
.wav (do you mean the file extension?)

**Comment by joelkraehemann** [comment]
Yes, this happens if the file is yet present. I provide a fix for this. An additional dialog asking to remove the file prior to export.

**Comment by joelkraehemann** [comment]
fixed by this commit:

https://github.com/gsequencer/gsequencer/commit/98c4fc005d0fef49afa09fa107821eae24413bef
